<?php


namespace App\Core\Formatter;

use App\Core\Components\EmailSender;
use Hyperf\Command\Command;
use Hyperf\Contract\ContainerInterface;
use Hyperf\Di\Annotation\Inject;
use Hyperf\HttpServer\Contract\RequestInterface;
use Hyperf\Utils\ApplicationContext;
use \Monolog\Formatter\LineFormatter as BaseLineFormatter;
use Symfony\Component\Console\CommandLoader\CommandLoaderInterface;

/**
 * 日志格式化，添加额外的字段
 * Class LineFormatter
 * @package App\Base\Formatter
 */
class MailerLineFormatter extends BaseLineFormatter
{
    /**
     * @Inject()
     * @var RequestInterface $request
     */
    protected $request;

    const NEW_FORMAT = "[%datetime%][%appid%][%pid%][%user%][%channel%][%level_name%] %message%\n";

    /**
     * LineFormatter constructor.
     * @param null $format
     * @param null $dateFormat
     * @param bool $allowInlineLineBreaks
     * @param bool $ignoreEmptyContextAndExtra
     */
    public function __construct($format = null, $dateFormat = null, $allowInlineLineBreaks = false, $ignoreEmptyContextAndExtra = false)
    {
        $format = $format ? $format : self::NEW_FORMAT;
        parent::__construct($format, $dateFormat, $allowInlineLineBreaks, $ignoreEmptyContextAndExtra);
    }

    /**
     * @param array $record
     * @return array|mixed|string|null
     */
    public function format(array $record)
    {
        $result = parent::format($record); // TODO: Change the autogenerated stub
        $appId = env('APP_NAME', '-');
        $pid = getmypid();
        $user = get_current_user();
        $result = preg_replace(['/%appid%/', '/%pid%/', '/%user%/'], [$appId, $pid, $user], $result);
        return $result;
    }
}